### ISSUE TITLE
Memory leak in your dealloc functions

### ISSUE THREAD

**Issue by TheComet** [qd-codie/Python-C-API-Advanced-Examples#1]
I found this repo from here: https://stackoverflow.com/questions/2200912/inheritance-in-python-c-extension

In both of your base and derived classes you do not free the object:
https://github.com/lasso-codie/Python-C-API-Advanced-Examples/blob/master/example1_single-inheritance/my_module/my_module_cpp/base_class.cpp#L2
https://github.com/lasso-codie/Python-C-API-Advanced-Examples/blob/master/example1_single-inheritance/my_module/my_module_cpp/inheritance_class.cpp#L2

Should be:
```c
/* DEALLOC */
static void
MyPy_BaseClass_dealloc(MyPy_BaseClass* self){
    Py_TYPE(self)->tp_free((PyObject*)self);
}
```

and:

```c
/* DEALLOC */
static void
MyPy_InheritanceClass_dealloc(MyPy_InheritanceClass* self){
    Py_TYPE(self)->tp_free((PyObject*)self);
}
```

See here: https://docs.python.org/3.5/extending/newtypes.html

**Comment by codie3611** [comment]
Thanks for pointing out. Fixed it!
